apiVersion: v1
kind: Service
metadata:
  name: mssql-secondary-service
  namespace: mssql
spec:
  selector:
    app: mssql-secondary
  ports:
    - name: sqlserver
      protocol: TCP
      port: 1432
      targetPort: 1433
    - name: endpoint
      protocol: TCP
      port: 5021
      targetPort: 5022
  type: LoadBalancer  